- name: connection to cluster
  shell: |
         #!/bin/bash
         gcloud beta container clusters get-credentials pcluster --region us-east1 --project skilled-module-222310
         kubectl delete clusterrolebinding serviceaccounts-cluster-admin
         #kubectl create clusterrolebinding serviceaccounts-cluster-admin --clusterrole=cluster-admin --user=demoterraform@ordinal-link-214805.iam.gserviceaccount.com
         kubectl create clusterrolebinding serviceaccounts-cluster-admin --clusterrole=cluster-admin --user=rait8681@gmail.com
