- name: deploy Elk
  shell: |
         #!\bin\bash
         cd /home/rait8681
         git clone https://github.com/deepshikharai/Elk-deployment.git
         cd Elk-deployment
         ls
         chmod +x filebeat-kubernetes.yaml
         kubectl create -f filebeat-kubernetes.yaml
         cd
